#spring:
#  cloud:
#    openservicebroker:
#      base-path: /geolocation-broker
geolocation:
  base-url: "examplebaseurl.com/"
  dashboard:
    base-url: "exampledashboardbaseurl.com/"
spring:
  cloud:
    openservicebroker:
      api-version: 2.14